version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=sequelizenode
      - DB_USER=postgres
      - DB_PASSWORD=261122
      - DB_SSL=false
    volumes:
      - .:/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 261122
      POSTGRES_DB: sequelizenode
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
