import { ApiStatus } from './ApiStatus'

export function Hero() {
  return <section className="hero" id="home"><div className="container"><div className="row align-items-center gy-5"><div className="col-lg-6"><div className="hero-copy"><div className="eyebrow"><span /> Built for modern backends</div><h1>Build secure multi-tenant applications <em>faster.</em></h1><p>A complete REST API demonstrating authentication, tenant isolation, role management and CRUD operations using modern backend architecture.</p><div className="hero-actions"><a className="btn btn-primary btn-lg" href="#api">Explore API <i className="bi bi-arrow-right ms-2" /></a><a className="btn btn-link btn-lg" href="https://github.com/Pedrohac7/Api" target="_blank" rel="noreferrer"><i className="bi bi-github me-2" />GitHub</a></div><div className="trust-line"><i className="bi bi-shield-check" /> Tenant-aware by design <span /> <i className="bi bi-check2-circle" /> JWT protected</div><ApiStatus /></div></div><div className="col-lg-6"><HeroDashboard /></div></div></div></section>
}

function HeroDashboard() {
  return <div className="hero-dashboard"><div className="window-bar"><span className="dot red" /><span className="dot amber" /><span className="dot green" /><div className="window-address">api.example.dev/dashboard</div></div><div className="dashboard-body"><aside><div className="mini-logo">N</div><i className="bi bi-grid-1x2-fill active" /><i className="bi bi-people" /><i className="bi bi-buildings" /><i className="bi bi-gear" /></aside><div className="hero-panel"><div className="panel-top"><div><small>Overview</small><strong>Good morning, Pedro</strong></div><span className="avatar">PA</span></div><div className="mini-stats"><MiniStat icon="bi-people" label="Clients" value="1,284" up="12.5%" /><MiniStat icon="bi-buildings" label="Tenants" value="24" up="8.2%" /><MiniStat icon="bi-activity" label="Requests" value="8.9k" up="18.4%" /></div><div className="chart-card"><div><strong>API activity</strong><small>Last 7 days</small></div><div className="chart"><span style={{height:'32%'}} /><span style={{height:'50%'}} /><span style={{height:'40%'}} /><span style={{height:'72%'}} /><span style={{height:'58%'}} /><span style={{height:'88%'}} /><span style={{height:'68%'}} /></div></div><div className="recent-title"><strong>Recent requests</strong><small>View all</small></div><div className="request"><span className="method get">GET</span><code>/api/clients</code><small>200</small></div><div className="request"><span className="method post">POST</span><code>/api/clients</code><small>201</small></div></div></div></div>
}
function MiniStat({ icon, label, value, up }: {icon:string;label:string;value:string;up:string}) { return <div className="mini-stat"><i className={`bi ${icon}`} /><small>{label}</small><strong>{value}</strong><span>↗ {up}</span></div> }
